name: Rebuild Bundles on Vapi Update

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  check-updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Check for updates in Vapi repository
        run: |
          git clone https://github.com/VapiAI/web.git
          cd web
          git fetch origin
          git log -1 --format="%H" > ../vapi-latest-commit.txt

      - name: Compare with last known commit
        id: compare
        run: |
          echo "Latest commit in Vapi repository:"
          cat ../vapi-latest-commit.txt
          if [ -f vapi-last-known-commit.txt ]; then
            echo "Last known commit:"
            cat vapi-last-known-commit.txt
            if cmp -s vapi-latest-commit.txt vapi-last-known-commit.txt; then
              echo "Vapi repository has not been updated."
              echo "updated=false" >> $GITHUB_ENV
            else
              echo "Vapi repository has been updated."
              echo "updated=true" >> $GITHUB_ENV
              cp vapi-latest-commit.txt vapi-last-known-commit.txt
            fi
          else
            cp vapi-latest-commit.txt vapi-last-known-commit.txt
            echo "First run, initializing commit tracking."
            echo "updated=true" >> $GITHUB_ENV

  build:
    needs: check-updates
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install npm-check-updates
        if: env.updated == 'true'
        run: npm install -g npm-check-updates

      - name: Update dependencies
        if: env.updated == 'true'
        run: ncu -u

      - name: Install dependencies
        if: env.updated == 'true'
        run: npm install

      - name: Run build script
        if: env.updated == 'true'
        run: npm run build

      - name: Commit and push changes
        if: env.updated == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add package.json package-lock.json
          git commit -m 'Automated build: update dependencies and rebuild bundles based on Vapi repo changes'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
